# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/FPGA/practice_project/blink_led_project/blink_led_bd/blink_led_bd.srcs/sources_1/bd/blink_led_bd/ip/blink_led_bd_processing_system7_0_0/blink_led_bd_processing_system7_0_0.xci
# IP: The module: 'blink_led_bd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/practice_project/blink_led_project/blink_led_bd/blink_led_bd.gen/sources_1/bd/blink_led_bd/ip/blink_led_bd_processing_system7_0_0/blink_led_bd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'blink_led_bd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/FPGA/practice_project/blink_led_project/blink_led_bd/blink_led_bd.srcs/sources_1/bd/blink_led_bd/ip/blink_led_bd_processing_system7_0_0/blink_led_bd_processing_system7_0_0.xci
# IP: The module: 'blink_led_bd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/practice_project/blink_led_project/blink_led_bd/blink_led_bd.gen/sources_1/bd/blink_led_bd/ip/blink_led_bd_processing_system7_0_0/blink_led_bd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'blink_led_bd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
