# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/HW/Zybo-Z7-Master.xdc

# Block Designs: bd/blink_led_bd/blink_led_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blink_led_bd || ORIG_REF_NAME==blink_led_bd} -quiet] -quiet

# IP: bd/blink_led_bd/ip/blink_led_bd_processing_system7_0_0/blink_led_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blink_led_bd_processing_system7_0_0 || ORIG_REF_NAME==blink_led_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/blink_led_bd/ip/blink_led_bd_blink_led_0_0/blink_led_bd_blink_led_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blink_led_bd_blink_led_0_0 || ORIG_REF_NAME==blink_led_bd_blink_led_0_0} -quiet] -quiet

# XDC: c:/FPGA/practice_project/blink_led_project/blink_led_bd/blink_led_bd.gen/sources_1/bd/blink_led_bd/blink_led_bd_ooc.xdc
